name: MacOS Build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: brew install ffmpeg libopenmpt
      - name: Build
        env:
          LIBRARY_PATH: /opt/homebrew/lib
          CPATH: /opt/homebrew/include
        run: cargo build --release
